---
- hosts: all
  gather_facts: true
  tasks:
    - debug:
        var: ansible_facts

    - name: Check if device is Cisco Switch or Ubuntu server
      debug:
        msg: >
          {{
            'This is a Cisco Switch running IOS.' if ansible_network_os == 'ios'
            else 'This is a Linux server running Ubuntu.'
          }}
      when: ansible_network_os == 'ios' or ansible_distribution == 'Ubuntu'

    - name: Gather IOS Facts 02
      ios_facts:
        gather_subset: all
      register: all_subset

    - name: Print Subset All 03
      debug:
        var: all_subset

    - name: Gather HW
      ios_facts:
        gather_subset: hardware
      register: hw
    - name: Print HW
      debug:
        var: hw

    - name: Gather Int
      ios_facts:
        gather_subset: interfaces
      register: int
    - name: Print Interfaces
      debug:
        var: int
