---
- name: Cisco
  hosts: all
  tasks:
    - name: Display group names
      debug:
        msg: "{{ group_names }}"
    - name: Display all groups and their hosts
      debug:
        var: groups
        
    - name: Cisco | Get ping response
      cisco.ios.ios_ping:
        dest: 10.1.255.1
      when: "'swt' not in group_names"
