---
- name: Cisco
  hosts: all
  tasks:
    - name: Display inventory hostname
      debug:
        msg: "{{ inventory_hostname }}"
    - name: Display all groups and their hosts
      debug:
        var: groups
        
    - name: Get ping response
      cisco.ios.ios_ping:
        dest: 10.1.255.1
      when: "'swt' not in inventory_hostname"
