---
- name: Cisco
  hosts: all
  tasks:
    - name: Create variable
      ansible.builtin.set_fact:
        host_list:
          - "ac-in-A05"

    - name: Create directory
      ansible.builtin.file:
        path: "/data/config/{{ item }}"
        owner: nobody
        group: nogroup
        mode: '0755'
        state: directory
      with_items: "{{ host_list }}"
      delegate_to: swt
